/**
 * Coach Insights — proactive insights generated by the background cron.
 * Fetched live, dismissible per-user.
 */
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";

export interface CoachInsight {
  id: string;
  user_id: string;
  type: string;
  severity: "info" | "warning" | "critical";
  category: string | null;
  title: string;
  body: string;
  source: Record<string, any>;
  created_at: string;
  dismissed_at: string | null;
  expires_at: string | null;
}

export function useCoachInsights() {
  const { user } = useAuth();
  const qc = useQueryClient();

  const list = useQuery({
    queryKey: ["coach_insights", user?.id],
    queryFn: async () => {
      if (!user?.id) return [] as CoachInsight[];
      const nowIso = new Date().toISOString();
      const { data, error } = await (supabase as any)
        .from("coach_insights")
        .select("*")
        .eq("user_id", user.id)
        .is("dismissed_at", null)
        .or(`expires_at.is.null,expires_at.gt.${nowIso}`)
        .order("created_at", { ascending: false })
        .limit(20);
      if (error) throw error;
      return (data ?? []) as CoachInsight[];
    },
    enabled: !!user?.id,
    staleTime: 60_000,
  });

  const dismiss = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await (supabase as any)
        .from("coach_insights")
        .update({ dismissed_at: new Date().toISOString() })
        .eq("id", id);
      if (error) throw error;
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["coach_insights", user?.id] }),
    onError: (e: any) => toast.error(e?.message ?? "Erreur"),
  });

  return {
    insights: list.data ?? [],
    isLoading: list.isLoading,
    dismiss: dismiss.mutateAsync,
  };
}