/**
 * CoachInsightsList — proactive insights generated by the background cron,
 * rendered as a compact stack inside the Coach drawer.
 */
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, X, AlertTriangle, Info, AlertCircle } from "lucide-react";
import { useCoachInsights } from "@/hooks/useCoachInsights";
import { cn } from "@/lib/utils";

const SEVERITY_META = {
  info: { icon: Info, cls: "text-primary border-primary/30 bg-primary/5" },
  warning: { icon: AlertTriangle, cls: "text-[hsl(40,100%,60%)] border-[hsl(40,100%,60%)]/30 bg-[hsl(40,100%,60%)]/5" },
  critical: { icon: AlertCircle, cls: "text-destructive border-destructive/30 bg-destructive/5" },
} as const;

export function CoachInsightsList() {
  const { insights, isLoading, dismiss } = useCoachInsights();

  if (isLoading || insights.length === 0) return null;

  return (
    <div className="border-b border-border/50 px-3 py-3 space-y-2">
      <div className="flex items-center gap-1.5 text-[10px] uppercase tracking-wider text-muted-foreground font-display">
        <Sparkles className="h-3 w-3" />
        Insights proactifs
      </div>
      <AnimatePresence initial={false}>
        {insights.slice(0, 5).map((ins) => {
          const meta = SEVERITY_META[ins.severity] ?? SEVERITY_META.info;
          const Icon = meta.icon;
          return (
            <motion.div
              key={ins.id}
              initial={{ opacity: 0, y: -4 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95 }}
              transition={{ duration: 0.15 }}
              className={cn("relative rounded-md border px-2.5 py-2 pr-7 text-xs", meta.cls)}
            >
              <div className="flex items-start gap-2">
                <Icon className="h-3.5 w-3.5 mt-0.5 shrink-0" />
                <div className="min-w-0">
                  <p className="font-medium leading-tight">{ins.title}</p>
                  <p className="text-muted-foreground mt-0.5 leading-snug">{ins.body}</p>
                </div>
              </div>
              <button
                onClick={() => dismiss(ins.id)}
                aria-label="Ignorer"
                className="absolute top-1.5 right-1.5 p-1 rounded hover:bg-foreground/10 transition-colors text-muted-foreground"
              >
                <X className="h-3 w-3" />
              </button>
            </motion.div>
          );
        })}
      </AnimatePresence>
    </div>
  );
}