-- 1. Add opt-out flag to notification_settings
ALTER TABLE public.notification_settings
  ADD COLUMN IF NOT EXISTS coach_proactive_enabled boolean NOT NULL DEFAULT true;

-- 2. coach_insights — proactive insights generated by cron
CREATE TABLE IF NOT EXISTS public.coach_insights (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type text NOT NULL DEFAULT 'pattern',
  severity text NOT NULL DEFAULT 'info',
  category text,
  title text NOT NULL,
  body text NOT NULL,
  source jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  dismissed_at timestamptz,
  expires_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_coach_insights_user_active
  ON public.coach_insights (user_id, created_at DESC)
  WHERE dismissed_at IS NULL;

ALTER TABLE public.coach_insights ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users view own insights"
  ON public.coach_insights FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users dismiss own insights"
  ON public.coach_insights FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users delete own insights"
  ON public.coach_insights FOR DELETE
  USING (auth.uid() = user_id);

-- 3. coach_cron_runs — execution log (admin-only)
CREATE TABLE IF NOT EXISTS public.coach_cron_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  job text NOT NULL,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  users_processed integer NOT NULL DEFAULT 0,
  insights_created integer NOT NULL DEFAULT 0,
  errors jsonb NOT NULL DEFAULT '[]'::jsonb,
  duration_ms integer
);

CREATE INDEX IF NOT EXISTS idx_coach_cron_runs_started
  ON public.coach_cron_runs (started_at DESC);

ALTER TABLE public.coach_cron_runs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins view cron runs"
  ON public.coach_cron_runs FOR SELECT
  USING (public.has_role(auth.uid(), 'admin'));