-- LES QUESTIONS DU JOURNAL
--
-- Quinze questions tournaient par langue, dans cinq categories heritees
-- d une application de developpement personnel : gratitude, stoic, cbt,
-- visualization, reflection. La rotation etant hash(jour, user) % 15, la
-- meme question revenait TOUS LES QUINZE JOURS.
--
-- Elles passent a cent soixante-neuf par langue, reparties en huit
-- familles. Le cycle passe de quinze jours a plus de cinq mois.
--
-- LE REGISTRE EST REFLEXIF, PAS DIRECTIF, et c est la seule regle qui
-- compte. « Qu est-ce qui ferait bouger ce chiffre cette semaine ? »
-- reclame une action ; « considères-tu avoir beaucoup depense depuis le
-- debut ? » invite a penser. Une question de journal ne demande jamais
-- ce qu on va faire, elle demande ce qu on voit. C est particulierement
-- vrai de la famille « pacte », qui parle des objectifs de
-- l utilisateur sans jamais lui suggerer quoi en faire.
--
-- LES HUIT FAMILLES, du plus grave au plus leger :
--   derniers_mots     ce qu on dirait s il ne restait qu une phrase
--   sensible          le soleil, la pluie, une odeur, une lumiere
--   les_autres        ce qu on doit, ce qu on cache, a qui
--   le_tu             ce qu on evite de regarder
--   le_temps          l enfant qu on etait, celui qu on sera
--   l_ordinaire       la texture d une journee
--   ce_que_tu_crois   ce qu on defendrait meme seul
--   le_pacte          ses propres objectifs, sans conseil
--
-- LES ANCIENNES SONT DESACTIVEES, PAS SUPPRIMEES. Elles ne tournent
-- plus, mais restent lisibles si l on veut y revenir : desactiver est
-- reversible, supprimer ne l est pas.

update public.journal_prompts
   set is_active = false
 where category in ('reflection', 'gratitude', 'stoic', 'visualization', 'cbt');

insert into public.journal_prompts (prompt, category, language) values
  ('Si, demain, tu venais à mourir, qu’aimerais-tu dire comme derniers mots à la personne à qui tu tiens le plus ?', 'derniers_mots', 'fr'),
  ('If you were to die tomorrow, what would you want to say to the person you care about most?', 'derniers_mots', 'en'),
  ('Qu’est-ce que tu regretterais de n’avoir jamais dit ?', 'derniers_mots', 'fr'),
  ('What would you regret never having said?', 'derniers_mots', 'en'),
  ('Qui viendrait à ton enterrement sans que tu t’y attendes ?', 'derniers_mots', 'fr'),
  ('Who would come to your funeral that you wouldn’t expect?', 'derniers_mots', 'en'),
  ('Qu’est-ce qu’on pourrait dire de toi qui serait vrai, et que tu n’aimerais pas entendre ?', 'derniers_mots', 'fr'),
  ('What could someone say about you that would be true, and that you wouldn’t like hearing?', 'derniers_mots', 'en'),
  ('Que veux-tu qu’il reste de toi dans dix ans ? Et dans cent ?', 'derniers_mots', 'fr'),
  ('What do you want left of you in ten years? In a hundred?', 'derniers_mots', 'en'),
  ('Y a-t-il quelqu’un que tu n’as jamais remercié ?', 'derniers_mots', 'fr'),
  ('Is there someone you never thanked?', 'derniers_mots', 'en'),
  ('Qu’est-ce que tu as reçu de quelqu’un et que tu n’as jamais rendu ?', 'derniers_mots', 'fr'),
  ('What did you receive from someone and never give back?', 'derniers_mots', 'en'),
  ('Quelle phrase, dite par quelqu’un d’autre, t’a suivi le plus longtemps ?', 'derniers_mots', 'fr'),
  ('Which sentence, spoken by someone else, has followed you longest?', 'derniers_mots', 'en'),
  ('À qui devrais-tu écrire, et à qui n’écriras-tu jamais ?', 'derniers_mots', 'fr'),
  ('Who should you write to, and who will you never write to?', 'derniers_mots', 'en'),
  ('Si tu ne pouvais transmettre qu’une seule chose, qu’est-ce que ce serait ?', 'derniers_mots', 'fr'),
  ('If you could pass on only one thing, what would it be?', 'derniers_mots', 'en'),
  ('Qu’est-ce que tu ferais de ta dernière journée si tu la savais dernière ?', 'derniers_mots', 'fr'),
  ('What would you do with your last day if you knew it was the last?', 'derniers_mots', 'en'),
  ('Quelle part de toi voudrais-tu que personne ne découvre après ?', 'derniers_mots', 'fr'),
  ('Which part of you would you rather no one discovered afterwards?', 'derniers_mots', 'en'),
  ('Qui te manque, et depuis combien de temps ?', 'derniers_mots', 'fr'),
  ('Who do you miss, and for how long now?', 'derniers_mots', 'en'),
  ('Si ta vie était racontée par quelqu’un qui t’aime, que dirait-il ? Et par quelqu’un qui ne t’aime pas ?', 'derniers_mots', 'fr'),
  ('If your life were told by someone who loves you, what would they say? And by someone who doesn’t?', 'derniers_mots', 'en'),
  ('Qu’est-ce que tu as pardonné sans le dire ?', 'derniers_mots', 'fr'),
  ('What have you forgiven without saying so?', 'derniers_mots', 'en'),
  ('Y a-t-il une porte que tu as fermée et que tu n’ouvriras plus ?', 'derniers_mots', 'fr'),
  ('Is there a door you closed that you’ll never open again?', 'derniers_mots', 'en'),
  ('Qu’est-ce que tu voudrais qu’on retienne de ta façon d’être, plutôt que de ce que tu as fait ?', 'derniers_mots', 'fr'),
  ('What would you want remembered about the way you were, rather than what you did?', 'derniers_mots', 'en'),
  ('Quelle conversation attends-tu d’avoir, et depuis quand ?', 'derniers_mots', 'fr'),
  ('Which conversation are you waiting to have, and since when?', 'derniers_mots', 'en'),
  ('Qu’est-ce qui, en toi, vient de quelqu’un d’autre ?', 'derniers_mots', 'fr'),
  ('What in you came from someone else?', 'derniers_mots', 'en'),
  ('Si tu pouvais reprendre une seule chose que tu as dite, laquelle ?', 'derniers_mots', 'fr'),
  ('If you could take back one thing you said, which would it be?', 'derniers_mots', 'en'),
  ('Que devrais-tu dire à quelqu’un pendant qu’il est encore temps ?', 'derniers_mots', 'fr'),
  ('What should you say to someone while there’s still time?', 'derniers_mots', 'en'),
  ('Qu’est-ce que ta présence change, autour de toi ?', 'derniers_mots', 'fr'),
  ('What does your presence change, around you?', 'derniers_mots', 'en'),
  ('Que t’évoque le soleil ?', 'sensible', 'fr'),
  ('What does the sun evoke in you?', 'sensible', 'en'),
  ('Quelle odeur te ramène quelque part, et où ?', 'sensible', 'fr'),
  ('What smell takes you back somewhere, and where?', 'sensible', 'en'),
  ('Quel bruit t’apaise sans que tu saches pourquoi ?', 'sensible', 'fr'),
  ('What sound calms you without your knowing why?', 'sensible', 'en'),
  ('Décris la lumière d’aujourd’hui.', 'sensible', 'fr'),
  ('Describe today’s light.', 'sensible', 'en'),
  ('Quelle est la dernière chose que tu as trouvée belle ?', 'sensible', 'fr'),
  ('What’s the last thing you found beautiful?', 'sensible', 'en'),
  ('Qu’est-ce que la pluie te fait, à toi ?', 'sensible', 'fr'),
  ('What does rain do to you, personally?', 'sensible', 'en'),
  ('Quelle couleur ne supportes-tu pas, et depuis quand ?', 'sensible', 'fr'),
  ('Which colour can’t you stand, and since when?', 'sensible', 'en'),
  ('Y a-t-il un endroit dont tu te souviens par sa température ?', 'sensible', 'fr'),
  ('Is there a place you remember by its temperature?', 'sensible', 'en'),
  ('Quel goût as-tu perdu, et lequel as-tu découvert tard ?', 'sensible', 'fr'),
  ('Which taste have you lost, and which did you discover late?', 'sensible', 'en'),
  ('Qu’est-ce que le silence te dit, quand il dure ?', 'sensible', 'fr'),
  ('What does silence tell you, when it lasts?', 'sensible', 'en'),
  ('Quelle chanson ne peux-tu plus écouter, et pourquoi ?', 'sensible', 'fr'),
  ('Which song can you no longer listen to, and why?', 'sensible', 'en'),
  ('Décris une chose que tu vois tous les jours sans la regarder.', 'sensible', 'fr'),
  ('Describe something you see every day without looking at it.', 'sensible', 'en'),
  ('Quelle matière aimes-tu toucher ?', 'sensible', 'fr'),
  ('What material do you like to touch?', 'sensible', 'en'),
  ('À quoi ressemble ta ville, la nuit, quand tu y es seul ?', 'sensible', 'fr'),
  ('What does your town look like at night, when you’re alone in it?', 'sensible', 'en'),
  ('Qu’est-ce qui, dehors, t’a arrêté récemment ?', 'sensible', 'fr'),
  ('What outside stopped you recently?', 'sensible', 'en'),
  ('Quel paysage t’habite ?', 'sensible', 'fr'),
  ('Which landscape lives in you?', 'sensible', 'en'),
  ('Qu’est-ce que tu entends, là, si tu t’arrêtes une minute ?', 'sensible', 'fr'),
  ('What can you hear, right now, if you stop for a minute?', 'sensible', 'en'),
  ('Quelle saison te ressemble le plus ?', 'sensible', 'fr'),
  ('Which season is most like you?', 'sensible', 'en'),
  ('Décris le visage de quelqu’un que tu connais par cœur.', 'sensible', 'fr'),
  ('Describe the face of someone you know by heart.', 'sensible', 'en'),
  ('Qu’est-ce qui te donne envie de rester dehors plus longtemps ?', 'sensible', 'fr'),
  ('What makes you want to stay outside longer?', 'sensible', 'en'),
  ('Quelle lumière trouves-tu triste ?', 'sensible', 'fr'),
  ('What kind of light do you find sad?', 'sensible', 'en'),
  ('Qu’est-ce que tu regardes quand tu ne penses à rien ?', 'sensible', 'fr'),
  ('What do you look at when you’re thinking of nothing?', 'sensible', 'en'),
  ('De qui te sens-tu responsable, sans qu’on te l’ait demandé ?', 'les_autres', 'fr'),
  ('Who do you feel responsible for, without having been asked?', 'les_autres', 'en'),
  ('Avec qui es-tu le plus toi-même, et pourquoi celui-là ?', 'les_autres', 'fr'),
  ('With whom are you most yourself, and why that person?', 'les_autres', 'en'),
  ('Qu’est-ce que tu n’oses pas demander, et à qui ?', 'les_autres', 'fr'),
  ('What don’t you dare ask, and of whom?', 'les_autres', 'en'),
  ('Qui t’a changé sans le savoir ?', 'les_autres', 'fr'),
  ('Who changed you without knowing it?', 'les_autres', 'en'),
  ('Quelle amitié as-tu laissée s’éteindre ?', 'les_autres', 'fr'),
  ('Which friendship did you let fade?', 'les_autres', 'en'),
  ('Qu’est-ce que les gens comprennent de travers, chez toi ?', 'les_autres', 'fr'),
  ('What do people get wrong about you?', 'les_autres', 'en'),
  ('Devant qui joues-tu un rôle ?', 'les_autres', 'fr'),
  ('In front of whom do you play a part?', 'les_autres', 'en'),
  ('Qui t’envie, à ton avis, et de quoi ?', 'les_autres', 'fr'),
  ('Who envies you, do you think, and for what?', 'les_autres', 'en'),
  ('Qu’est-ce que tu donnes que personne ne remarque ?', 'les_autres', 'fr'),
  ('What do you give that no one notices?', 'les_autres', 'en'),
  ('À qui ressembles-tu plus que tu ne voudrais ?', 'les_autres', 'fr'),
  ('Who do you resemble more than you’d like?', 'les_autres', 'en'),
  ('Quelle rencontre a tenu à un fil ?', 'les_autres', 'fr'),
  ('Which meeting hung by a thread?', 'les_autres', 'en'),
  ('Qu’est-ce que tu attends des autres que tu ne leur dis pas ?', 'les_autres', 'fr'),
  ('What do you expect from others that you never tell them?', 'les_autres', 'en'),
  ('Qui t’a fait confiance en premier ?', 'les_autres', 'fr'),
  ('Who trusted you first?', 'les_autres', 'en'),
  ('Avec qui le silence est-il confortable ?', 'les_autres', 'fr'),
  ('With whom is silence comfortable?', 'les_autres', 'en'),
  ('Qu’est-ce que tu reproches à quelqu’un et que tu fais aussi ?', 'les_autres', 'fr'),
  ('What do you hold against someone that you also do?', 'les_autres', 'en'),
  ('De qui t’es-tu éloigné pour de bonnes raisons ?', 'les_autres', 'fr'),
  ('Who did you move away from for good reasons?', 'les_autres', 'en'),
  ('Qui appellerais-tu à trois heures du matin ?', 'les_autres', 'fr'),
  ('Who would you call at three in the morning?', 'les_autres', 'en'),
  ('Qu’est-ce que ta famille t’a transmis sans le vouloir ?', 'les_autres', 'fr'),
  ('What did your family pass on to you without meaning to?', 'les_autres', 'en'),
  ('Devant qui as-tu honte, et de quoi exactement ?', 'les_autres', 'fr'),
  ('In front of whom are you ashamed, and of what exactly?', 'les_autres', 'en'),
  ('Qui aurait besoin que tu prennes de ses nouvelles ?', 'les_autres', 'fr'),
  ('Who could use hearing from you?', 'les_autres', 'en'),
  ('Qu’est-ce que tu pardonnes facilement, et qu’est-ce que tu ne pardonnes pas ?', 'les_autres', 'fr'),
  ('What do you forgive easily, and what do you not forgive?', 'les_autres', 'en'),
  ('Quelle place occupes-tu dans la vie de quelqu’un, sans le savoir ?', 'les_autres', 'fr'),
  ('What place do you hold in someone’s life, without knowing it?', 'les_autres', 'en'),
  ('Qu’est-ce que tu évites de regarder en ce moment ?', 'le_tu', 'fr'),
  ('What are you avoiding looking at right now?', 'le_tu', 'en'),
  ('De quoi as-tu peur, quand personne ne demande ?', 'le_tu', 'fr'),
  ('What are you afraid of, when nobody’s asking?', 'le_tu', 'en'),
  ('Quel mensonge te racontes-tu, et depuis combien de temps ?', 'le_tu', 'fr'),
  ('What lie do you tell yourself, and for how long?', 'le_tu', 'en'),
  ('Qu’est-ce que tu n’as jamais dit à voix haute ?', 'le_tu', 'fr'),
  ('What have you never said out loud?', 'le_tu', 'en'),
  ('De quoi as-tu honte qui n’en vaut probablement pas la peine ?', 'le_tu', 'fr'),
  ('What are you ashamed of that probably isn’t worth it?', 'le_tu', 'en'),
  ('Qu’est-ce que tu remets à demain depuis des années ?', 'le_tu', 'fr'),
  ('What have you been putting off for years?', 'le_tu', 'en'),
  ('Quelle part de ta vie ne montres-tu à personne ?', 'le_tu', 'fr'),
  ('Which part of your life do you show no one?', 'le_tu', 'en'),
  ('Qu’est-ce qui te met en colère et que tu déguises en autre chose ?', 'le_tu', 'fr'),
  ('What angers you that you disguise as something else?', 'le_tu', 'en'),
  ('Qu’est-ce que tu ferais si tu étais sûr que personne ne le saurait ?', 'le_tu', 'fr'),
  ('What would you do if you were sure no one would know?', 'le_tu', 'en'),
  ('Quelle vérité te concernant préfères-tu ne pas creuser ?', 'le_tu', 'fr'),
  ('Which truth about yourself would you rather not dig into?', 'le_tu', 'en'),
  ('Qu’est-ce que tu fuis en t’occupant ?', 'le_tu', 'fr'),
  ('What are you running from by keeping busy?', 'le_tu', 'en'),
  ('Quel besoin refuses-tu de reconnaître ?', 'le_tu', 'fr'),
  ('Which need do you refuse to acknowledge?', 'le_tu', 'en'),
  ('Qu’est-ce qui, chez toi, t’étonne encore ?', 'le_tu', 'fr'),
  ('What about yourself still surprises you?', 'le_tu', 'en'),
  ('De quoi te sens-tu coupable sans avoir rien fait ?', 'le_tu', 'fr'),
  ('What do you feel guilty about without having done anything?', 'le_tu', 'en'),
  ('Quelle envie te fait honte ?', 'le_tu', 'fr'),
  ('Which desire embarrasses you?', 'le_tu', 'en'),
  ('Qu’est-ce que tu tolères que tu ne devrais pas ?', 'le_tu', 'fr'),
  ('What do you tolerate that you shouldn’t?', 'le_tu', 'en'),
  ('Quel jugement portes-tu sur toi que tu ne porterais sur personne d’autre ?', 'le_tu', 'fr'),
  ('What judgement do you pass on yourself that you’d pass on no one else?', 'le_tu', 'en'),
  ('Qu’est-ce que tu attends pour te sentir autorisé ?', 'le_tu', 'fr'),
  ('What are you waiting for in order to feel allowed?', 'le_tu', 'en'),
  ('Quelle question évites-tu depuis le début de ce journal ?', 'le_tu', 'fr'),
  ('Which question have you been avoiding since you started this journal?', 'le_tu', 'en'),
  ('Qu’est-ce qui te fatigue sans que tu l’aies décidé ?', 'le_tu', 'fr'),
  ('What tires you without your having chosen it?', 'le_tu', 'en'),
  ('De quoi te protèges-tu qui n’existe peut-être plus ?', 'le_tu', 'fr'),
  ('What are you protecting yourself from that may no longer exist?', 'le_tu', 'en'),
  ('Qu’est-ce que l’enfant que tu étais penserait de toi ?', 'le_temps', 'fr'),
  ('What would the child you were think of you?', 'le_temps', 'en'),
  ('Quel âge as-tu à l’intérieur ?', 'le_temps', 'fr'),
  ('How old are you on the inside?', 'le_temps', 'en'),
  ('Quelle année de ta vie recommencerais-tu ?', 'le_temps', 'fr'),
  ('Which year of your life would you live again?', 'le_temps', 'en'),
  ('Qu’est-ce que tu croyais savoir à vingt ans ?', 'le_temps', 'fr'),
  ('What did you think you knew at twenty?', 'le_temps', 'en'),
  ('De quoi te souviendras-tu de cette semaine, dans dix ans ?', 'le_temps', 'fr'),
  ('What will you remember from this week, in ten years?', 'le_temps', 'en'),
  ('Qu’est-ce qui a mis longtemps à devenir évident ?', 'le_temps', 'fr'),
  ('What took a long time to become obvious?', 'le_temps', 'en'),
  ('Quel souvenir revient sans que tu l’appelles ?', 'le_temps', 'fr'),
  ('Which memory comes back without being called?', 'le_temps', 'en'),
  ('Qu’est-ce que tu as arrêté d’attendre ?', 'le_temps', 'fr'),
  ('What have you stopped waiting for?', 'le_temps', 'en'),
  ('À quoi ressemblait ta chambre quand tu avais dix ans ?', 'le_temps', 'fr'),
  ('What did your room look like when you were ten?', 'le_temps', 'en'),
  ('Qu’est-ce qui a disparu de ta vie sans que tu t’en aperçoives ?', 'le_temps', 'fr'),
  ('What disappeared from your life without your noticing?', 'le_temps', 'en'),
  ('Quelle décision, prise vite, a tout changé ?', 'le_temps', 'fr'),
  ('Which decision, made quickly, changed everything?', 'le_temps', 'en'),
  ('Qu’est-ce que tu diras de cette période, plus tard ?', 'le_temps', 'fr'),
  ('What will you say about this period, later?', 'le_temps', 'en'),
  ('Quel moment aimerais-tu pouvoir revivre une heure ?', 'le_temps', 'fr'),
  ('Which moment would you like to relive for an hour?', 'le_temps', 'en'),
  ('Qu’est-ce qui te paraissait immense et te paraît petit aujourd’hui ?', 'le_temps', 'fr'),
  ('What seemed enormous and seems small today?', 'le_temps', 'en'),
  ('Quelle habitude as-tu depuis si longtemps que tu ne la vois plus ?', 'le_temps', 'fr'),
  ('Which habit have you had so long you no longer see it?', 'le_temps', 'en'),
  ('Qu’est-ce que tu as commencé sans savoir que ça durerait ?', 'le_temps', 'fr'),
  ('What did you start without knowing it would last?', 'le_temps', 'en'),
  ('De quoi ta vie d’il y a cinq ans te semble-t-elle faite ?', 'le_temps', 'fr'),
  ('What does your life five years ago seem made of?', 'le_temps', 'en'),
  ('Qu’est-ce que tu voudrais dire au toi de l’année prochaine ?', 'le_temps', 'fr'),
  ('What would you like to say to next year’s you?', 'le_temps', 'en'),
  ('Quel moment banal est devenu important après coup ?', 'le_temps', 'fr'),
  ('Which ordinary moment became important afterwards?', 'le_temps', 'en'),
  ('Qu’est-ce qui, chez toi, n’a jamais changé ?', 'le_temps', 'fr'),
  ('What about you has never changed?', 'le_temps', 'en'),
  ('Quelle porte s’est fermée sans que tu l’entendes ?', 'le_temps', 'fr'),
  ('Which door closed without your hearing it?', 'le_temps', 'en'),
  ('Comment s’est passée ta journée, vraiment ?', 'l_ordinaire', 'fr'),
  ('How was your day, really?', 'l_ordinaire', 'en'),
  ('Qu’est-ce que tu as fait aujourd’hui qui ne compte pour personne ?', 'l_ordinaire', 'fr'),
  ('What did you do today that counts for no one?', 'l_ordinaire', 'en'),
  ('Quel geste répètes-tu tous les jours sans y penser ?', 'l_ordinaire', 'fr'),
  ('Which gesture do you repeat every day without thinking?', 'l_ordinaire', 'en'),
  ('Qu’est-ce qui t’a fait sourire cette semaine ?', 'l_ordinaire', 'fr'),
  ('What made you smile this week?', 'l_ordinaire', 'en'),
  ('À quoi ressemble ta première heure du matin ?', 'l_ordinaire', 'fr'),
  ('What does your first hour of the morning look like?', 'l_ordinaire', 'en'),
  ('Qu’est-ce que tu manges quand personne ne regarde ?', 'l_ordinaire', 'fr'),
  ('What do you eat when no one’s watching?', 'l_ordinaire', 'en'),
  ('Quelle petite chose t’a agacé aujourd’hui ?', 'l_ordinaire', 'fr'),
  ('What small thing annoyed you today?', 'l_ordinaire', 'en'),
  ('Où vas-tu quand tu veux être tranquille ?', 'l_ordinaire', 'fr'),
  ('Where do you go when you want to be left alone?', 'l_ordinaire', 'en'),
  ('Qu’est-ce que tu remets toujours au même endroit ?', 'l_ordinaire', 'fr'),
  ('What do you always put back in the same place?', 'l_ordinaire', 'en'),
  ('Comment sais-tu que tu es fatigué ?', 'l_ordinaire', 'fr'),
  ('How do you know when you’re tired?', 'l_ordinaire', 'en'),
  ('Qu’est-ce que tu fais quand tu ne sais pas quoi faire ?', 'l_ordinaire', 'fr'),
  ('What do you do when you don’t know what to do?', 'l_ordinaire', 'en'),
  ('Quel objet ne jetterais-tu pas, même sans valeur ?', 'l_ordinaire', 'fr'),
  ('Which object wouldn’t you throw away, even worthless?', 'l_ordinaire', 'en'),
  ('À quoi occupes-tu tes trajets ?', 'l_ordinaire', 'fr'),
  ('What do you fill your journeys with?', 'l_ordinaire', 'en'),
  ('Qu’est-ce qui rend une journée bonne, chez toi ?', 'l_ordinaire', 'fr'),
  ('What makes a day good, for you?', 'l_ordinaire', 'en'),
  ('Quelle est ta dernière pensée avant de dormir, en général ?', 'l_ordinaire', 'fr'),
  ('What’s your last thought before sleeping, usually?', 'l_ordinaire', 'en'),
  ('Qu’est-ce que tu reportes chaque semaine ?', 'l_ordinaire', 'fr'),
  ('What do you postpone every week?', 'l_ordinaire', 'en'),
  ('Qu’as-tu appris cette semaine sans le chercher ?', 'l_ordinaire', 'fr'),
  ('What did you learn this week without looking for it?', 'l_ordinaire', 'en'),
  ('Qu’est-ce qui t’a coûté plus d’énergie que prévu ?', 'l_ordinaire', 'fr'),
  ('What cost you more energy than expected?', 'l_ordinaire', 'en'),
  ('Quel moment de la journée préfères-tu, et depuis quand ?', 'l_ordinaire', 'fr'),
  ('Which time of day do you prefer, and since when?', 'l_ordinaire', 'en'),
  ('Qu’est-ce que tu as remis à sa place aujourd’hui, au propre ou au figuré ?', 'l_ordinaire', 'fr'),
  ('What did you put back in its place today, literally or otherwise?', 'l_ordinaire', 'en'),
  ('Qu’est-ce qui te manque, là, tout de suite, de très concret ?', 'l_ordinaire', 'fr'),
  ('What do you miss, right now, something very concrete?', 'l_ordinaire', 'en'),
  ('Qu’est-ce que tu défendrais même seul ?', 'ce_que_tu_crois', 'fr'),
  ('What would you defend even alone?', 'ce_que_tu_crois', 'en'),
  ('Sur quoi as-tu changé d’avis, et qu’est-ce qui t’a fait changer ?', 'ce_que_tu_crois', 'fr'),
  ('What did you change your mind about, and what changed it?', 'ce_que_tu_crois', 'en'),
  ('Qu’est-ce qui compte pour toi et que tu n’arrives pas à expliquer ?', 'ce_que_tu_crois', 'fr'),
  ('What matters to you that you can’t explain?', 'ce_que_tu_crois', 'en'),
  ('Qu’est-ce que tu appelles réussir ?', 'ce_que_tu_crois', 'fr'),
  ('What do you call succeeding?', 'ce_que_tu_crois', 'en'),
  ('Qu’est-ce qui te paraît insupportable chez les autres, et pourquoi ce point-là ?', 'ce_que_tu_crois', 'fr'),
  ('What seems unbearable to you in others, and why that particular thing?', 'ce_que_tu_crois', 'en'),
  ('Crois-tu que les gens changent ?', 'ce_que_tu_crois', 'fr'),
  ('Do you believe people change?', 'ce_que_tu_crois', 'en'),
  ('Qu’est-ce que tu ferais de ton temps si l’argent ne comptait pas ?', 'ce_que_tu_crois', 'fr'),
  ('What would you do with your time if money didn’t count?', 'ce_que_tu_crois', 'en'),
  ('Qu’est-ce qui te semble juste et que la loi ne dit pas ?', 'ce_que_tu_crois', 'fr'),
  ('What seems right to you that the law doesn’t say?', 'ce_que_tu_crois', 'en'),
  ('Quelle idée reçue as-tu longtemps acceptée ?', 'ce_que_tu_crois', 'fr'),
  ('Which received idea did you accept for a long time?', 'ce_que_tu_crois', 'en'),
  ('Qu’est-ce que tu admires chez quelqu’un que tu n’aimes pas ?', 'ce_que_tu_crois', 'fr'),
  ('What do you admire in someone you don’t like?', 'ce_que_tu_crois', 'en'),
  ('À quoi reconnais-tu quelqu’un de bien ?', 'ce_que_tu_crois', 'fr'),
  ('How do you recognise a good person?', 'ce_que_tu_crois', 'en'),
  ('Qu’est-ce que tu refuserais de faire, même bien payé ?', 'ce_que_tu_crois', 'fr'),
  ('What would you refuse to do, even well paid?', 'ce_que_tu_crois', 'en'),
  ('Qu’est-ce qui te fait douter de ce que tu crois ?', 'ce_que_tu_crois', 'fr'),
  ('What makes you doubt what you believe?', 'ce_que_tu_crois', 'en'),
  ('Que penses-tu du hasard ?', 'ce_que_tu_crois', 'fr'),
  ('What do you make of chance?', 'ce_que_tu_crois', 'en'),
  ('Qu’est-ce que tu trouves surestimé ?', 'ce_que_tu_crois', 'fr'),
  ('What do you find overrated?', 'ce_que_tu_crois', 'en'),
  ('Qu’est-ce que tu voudrais transmettre comme façon de voir ?', 'ce_que_tu_crois', 'fr'),
  ('What way of seeing would you like to pass on?', 'ce_que_tu_crois', 'en'),
  ('Qu’est-ce qui te met d’accord avec toi-même ?', 'ce_que_tu_crois', 'fr'),
  ('What puts you at peace with yourself?', 'ce_que_tu_crois', 'en'),
  ('Peut-on aimer quelqu’un et lui en vouloir longtemps ?', 'ce_que_tu_crois', 'fr'),
  ('Can you love someone and resent them for a long time?', 'ce_que_tu_crois', 'en'),
  ('Qu’est-ce qui vaut la peine d’être difficile ?', 'ce_que_tu_crois', 'fr'),
  ('What’s worth being difficult?', 'ce_que_tu_crois', 'en'),
  ('Qu’est-ce que tu crois aujourd’hui que tu ne croyais pas il y a dix ans ?', 'ce_que_tu_crois', 'fr'),
  ('What do you believe today that you didn’t ten years ago?', 'ce_que_tu_crois', 'en'),
  ('Considères-tu avoir beaucoup dépensé depuis le début ?', 'le_pacte', 'fr'),
  ('Do you consider that you’ve spent a lot since the beginning?', 'le_pacte', 'en'),
  ('Quel objectif portes-tu par habitude plus que par envie ?', 'le_pacte', 'fr'),
  ('Which goal are you carrying out of habit more than desire?', 'le_pacte', 'en'),
  ('Qu’est-ce que ton pacte dit de toi, vu de l’extérieur ?', 'le_pacte', 'fr'),
  ('What does your pact say about you, seen from outside?', 'le_pacte', 'en'),
  ('Y a-t-il un objectif que tu garderais si tu ne devais en garder qu’un ?', 'le_pacte', 'fr'),
  ('Is there one goal you’d keep if you could keep only one?', 'le_pacte', 'en'),
  ('Qu’est-ce que tu t’es promis et que tu ne veux plus vraiment ?', 'le_pacte', 'fr'),
  ('What did you promise yourself and no longer really want?', 'le_pacte', 'en'),
  ('Comment te sens-tu face à ce que tu as terminé ?', 'le_pacte', 'fr'),
  ('How do you feel about what you’ve finished?', 'le_pacte', 'en'),
  ('Qu’est-ce que l’argent représente pour toi en ce moment ?', 'le_pacte', 'fr'),
  ('What does money represent for you at the moment?', 'le_pacte', 'en'),
  ('Quel objectif t’a appris quelque chose que tu n’attendais pas ?', 'le_pacte', 'fr'),
  ('Which goal taught you something you weren’t expecting?', 'le_pacte', 'en'),
  ('Es-tu d’accord avec la personne qui a écrit ce pacte ?', 'le_pacte', 'fr'),
  ('Do you agree with the person who wrote this pact?', 'le_pacte', 'en'),
  ('Qu’est-ce que tu as abandonné, et est-ce que ça te manque ?', 'le_pacte', 'fr'),
  ('What have you given up, and do you miss it?', 'le_pacte', 'en'),
  ('Qu’est-ce qui te tient encore là-dedans ?', 'le_pacte', 'fr'),
  ('What still holds you in all this?', 'le_pacte', 'en'),
  ('Ce que tu poursuis vient-il de toi ?', 'le_pacte', 'fr'),
  ('Does what you’re pursuing come from you?', 'le_pacte', 'en'),
  ('Qu’est-ce que ton corps te dit de cette période ?', 'le_pacte', 'fr'),
  ('What is your body telling you about this period?', 'le_pacte', 'en'),
  ('Quelle dépense ne regrettes-tu pas du tout ?', 'le_pacte', 'fr'),
  ('Which expense do you not regret at all?', 'le_pacte', 'en'),
  ('Qu’est-ce que tu ferais de ces objectifs si personne ne les voyait ?', 'le_pacte', 'fr'),
  ('What would you do with these goals if no one could see them?', 'le_pacte', 'en'),
  ('Qu’est-ce qui, dans ta vie, ne rentre dans aucun objectif ?', 'le_pacte', 'fr'),
  ('What in your life fits into no goal at all?', 'le_pacte', 'en'),
  ('Comment vis-tu le fait de mesurer tout ça ?', 'le_pacte', 'fr'),
  ('How do you feel about measuring all this?', 'le_pacte', 'en'),
  ('Qu’est-ce que tu attendais en commençant, et qu’attends-tu maintenant ?', 'le_pacte', 'fr'),
  ('What were you expecting when you started, and what do you expect now?', 'le_pacte', 'en'),
  ('Y a-t-il un chiffre qui te suit plus que les autres ?', 'le_pacte', 'fr'),
  ('Is there one number that follows you more than the others?', 'le_pacte', 'en'),
  ('Qu’est-ce que tu te dirais si tu regardais ce pacte dans cinq ans ?', 'le_pacte', 'fr'),
  ('What would you tell yourself looking at this pact in five years?', 'le_pacte', 'en');
